name: sms_autofill
version: 0.0.1
description: SMS ile gelen OTP kodunun dinlenebilmesi icin olusturulan bir pakettir.

publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
